/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.main.java.restaurant.form;


import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import src.main.java.restaurant.bo.ActionType;
import src.main.java.restaurant.bo.MenuDayBO;

import src.main.java.restaurant.dto.MenuPlatoDTO;

/**
 *
 * @author rotse
 */
public class MenuDayForm extends javax.swing.JFrame {

    
    
    public MenuDayForm() {
        initComponents();
    
        
                
        setTitle("RESTAURANTE NESTOR");
          setLayout(null);
        setSize(650, 500);
        setLocationRelativeTo(null);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLIngresoDescrip = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        btnMostraFecha = new javax.swing.JButton();
        jLFecha = new javax.swing.JLabel();
        jTextDescrip = new javax.swing.JTextField();
        btnAgrePlato = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMenuDia = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("AGREGAR MENU DEL DIA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 28, -1, -1));

        jLabel2.setText("INGRESE FECHA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 100, 141, -1));

        jLIngresoDescrip.setText("INGRESE DESCRIPCION");
        jPanel1.add(jLIngresoDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 100, -1, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 333, -1, -1));

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 333, -1, -1));
        jPanel1.add(jDateChooserFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 128, 45, -1));

        btnMostraFecha.setText("Fecha");
        btnMostraFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostraFechaActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostraFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 128, -1, -1));
        jPanel1.add(jLFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 128, 96, 32));

        jTextDescrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescripActionPerformed(evt);
            }
        });
        jPanel1.add(jTextDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 128, 175, -1));

        btnAgrePlato.setText("AGREGAR PLATO");
        btnAgrePlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgrePlatoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgrePlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 178, -1, -1));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 333, -1, -1));

        jTableMenuDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "CATEGORIA", "PRECIO", "TIEMPO DE ESPERA", "RECETA"
            }
        ));
        jScrollPane1.setViewportView(jTableMenuDia);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 517, 84));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MainMenuForm volver = new MainMenuForm();
        volver.setVisible(true);
        dispose();
       
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
             DefaultTableModel tablaplato = (DefaultTableModel) MenuDayForm.jTableMenuDia.getModel();
        List<MenuPlatoDTO> menuPlatoList = new ArrayList();
        for (int i = 0; i < tablaplato.getDataVector().size(); i++) {
            Vector vector= (Vector) tablaplato.getDataVector().get(i);
         MenuPlatoDTO menuPlatoDTO =   menuPlatoDTO = new MenuPlatoDTO();
        
         menuPlatoDTO.setDescripcionMenu(jTextDescrip.getText());
         menuPlatoDTO.setFechaMenu(jLFecha.getText());

         
        for (int x = 0; x <= vector.size(); x++) {
            switch (x) {
                    case 0:
                        menuPlatoDTO.setNombrePlato((String) vector.elementAt(x));
                        break;
                    case 1:
                        menuPlatoDTO.setCategoria((String) vector.elementAt(x));
                        break;
                    case 2:
                        menuPlatoDTO.setPrecio(Double.valueOf((String) vector.elementAt(x)));
                        break;
                    case 3:
                         menuPlatoDTO.setTiempoEspera(Integer.valueOf((String) vector.elementAt(x)));
                        break;
                    case 4:
                       menuPlatoDTO.setRecetaPlato((String) vector.elementAt(x));
                        break;
                    default:
                    // code block
                }
            }
            menuPlatoList.add(menuPlatoDTO);
        }
 
      
        MenuDayBO menuDayBo = new MenuDayBO();
       menuDayBo.actionMenu(ActionType.save, menuPlatoList);
        
         
     
    }//GEN-LAST:event_btnGuardarActionPerformed

   
    private void btnMostraFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostraFechaActionPerformed
       
        String dia = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
        String mes = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.MONTH));
        String year = Integer.toString(jDateChooserFecha.getCalendar().get(Calendar.YEAR));
        String fecha = (year + "-" + mes + "-" + dia);
        jLFecha.setText(fecha); 
     
     
    }//GEN-LAST:event_btnMostraFechaActionPerformed

    private void jTextDescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescripActionPerformed

    private void btnAgrePlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgrePlatoActionPerformed
        PlatoDayForm agregarplato = new PlatoDayForm();
        agregarplato.setVisible(true);
        
               
    }//GEN-LAST:event_btnAgrePlatoActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
       
        this.jTableMenuDia.remove(this.jTableMenuDia);
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDayForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDayForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgrePlato;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostraFecha;
    private javax.swing.JButton btnVolver;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLFecha;
    private javax.swing.JLabel jLIngresoDescrip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableMenuDia;
    private javax.swing.JTextField jTextDescrip;
    // End of variables declaration//GEN-END:variables
}
